### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Meligy** [angular-university/angular-ngrx-course#3]
Hello,
What's the license of this repository? Is only for those who bought the course? Can it be . used for personal learning without buying the course? Can it be referenced in other blog posts / conference talks with attribution/link?

Thanks a lot.

Cheers,

**Comment by jhades** [comment]
Hello @Meligy, sure no problem, all code repositories for the Angular University are meant to be used for all the purposes you listed, I just added a MIT license for this one. 

I will add the license for all other repos during the upcoming upgrade to Angular 7. Thanks and Kind Regards, Vasco
